// Code generated by protoc-gen-go. DO NOT EDIT.
// source: userfav.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserFavRequest struct {
	UserId               int32    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	GoodsId              int32    `protobuf:"varint,2,opt,name=goodsId,proto3" json:"goodsId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserFavRequest) Reset()         { *m = UserFavRequest{} }
func (m *UserFavRequest) String() string { return proto.CompactTextString(m) }
func (*UserFavRequest) ProtoMessage()    {}
func (*UserFavRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_618b5697b793e087, []int{0}
}

func (m *UserFavRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserFavRequest.Unmarshal(m, b)
}
func (m *UserFavRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserFavRequest.Marshal(b, m, deterministic)
}
func (m *UserFavRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserFavRequest.Merge(m, src)
}
func (m *UserFavRequest) XXX_Size() int {
	return xxx_messageInfo_UserFavRequest.Size(m)
}
func (m *UserFavRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserFavRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserFavRequest proto.InternalMessageInfo

func (m *UserFavRequest) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *UserFavRequest) GetGoodsId() int32 {
	if m != nil {
		return m.GoodsId
	}
	return 0
}

type UserFavResponse struct {
	UserId               int32    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	GoodsId              int32    `protobuf:"varint,2,opt,name=goodsId,proto3" json:"goodsId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserFavResponse) Reset()         { *m = UserFavResponse{} }
func (m *UserFavResponse) String() string { return proto.CompactTextString(m) }
func (*UserFavResponse) ProtoMessage()    {}
func (*UserFavResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_618b5697b793e087, []int{1}
}

func (m *UserFavResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserFavResponse.Unmarshal(m, b)
}
func (m *UserFavResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserFavResponse.Marshal(b, m, deterministic)
}
func (m *UserFavResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserFavResponse.Merge(m, src)
}
func (m *UserFavResponse) XXX_Size() int {
	return xxx_messageInfo_UserFavResponse.Size(m)
}
func (m *UserFavResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserFavResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserFavResponse proto.InternalMessageInfo

func (m *UserFavResponse) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *UserFavResponse) GetGoodsId() int32 {
	if m != nil {
		return m.GoodsId
	}
	return 0
}

type UserFavListResponse struct {
	Total                int32              `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Data                 []*UserFavResponse `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *UserFavListResponse) Reset()         { *m = UserFavListResponse{} }
func (m *UserFavListResponse) String() string { return proto.CompactTextString(m) }
func (*UserFavListResponse) ProtoMessage()    {}
func (*UserFavListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_618b5697b793e087, []int{2}
}

func (m *UserFavListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserFavListResponse.Unmarshal(m, b)
}
func (m *UserFavListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserFavListResponse.Marshal(b, m, deterministic)
}
func (m *UserFavListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserFavListResponse.Merge(m, src)
}
func (m *UserFavListResponse) XXX_Size() int {
	return xxx_messageInfo_UserFavListResponse.Size(m)
}
func (m *UserFavListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserFavListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserFavListResponse proto.InternalMessageInfo

func (m *UserFavListResponse) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *UserFavListResponse) GetData() []*UserFavResponse {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*UserFavRequest)(nil), "UserFavRequest")
	proto.RegisterType((*UserFavResponse)(nil), "UserFavResponse")
	proto.RegisterType((*UserFavListResponse)(nil), "UserFavListResponse")
}

func init() { proto.RegisterFile("userfav.proto", fileDescriptor_618b5697b793e087) }

var fileDescriptor_618b5697b793e087 = []byte{
	// 261 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x2d, 0x4e, 0x2d,
	0x4a, 0x4b, 0x2c, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x97, 0x92, 0x4e, 0xcf, 0xcf, 0x4f, 0xcf,
	0x49, 0xd5, 0x07, 0xf3, 0x92, 0x4a, 0xd3, 0xf4, 0x53, 0x73, 0x0b, 0x4a, 0x2a, 0x21, 0x92, 0x4a,
	0x4e, 0x5c, 0x7c, 0xa1, 0xc5, 0xa9, 0x45, 0x6e, 0x89, 0x65, 0x41, 0xa9, 0x85, 0xa5, 0xa9, 0xc5,
	0x25, 0x42, 0x62, 0x5c, 0x6c, 0x20, 0xfd, 0x9e, 0x29, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0xac, 0x41,
	0x50, 0x9e, 0x90, 0x04, 0x17, 0x7b, 0x7a, 0x7e, 0x7e, 0x4a, 0xb1, 0x67, 0x8a, 0x04, 0x13, 0x58,
	0x02, 0xc6, 0x55, 0x72, 0xe6, 0xe2, 0x87, 0x9b, 0x51, 0x5c, 0x90, 0x9f, 0x57, 0x9c, 0x4a, 0x86,
	0x21, 0x81, 0x5c, 0xc2, 0x50, 0x43, 0x7c, 0x32, 0x8b, 0x4b, 0xe0, 0x06, 0x89, 0x70, 0xb1, 0x96,
	0xe4, 0x97, 0x24, 0xe6, 0x40, 0xcd, 0x81, 0x70, 0x84, 0x54, 0xb8, 0x58, 0x52, 0x12, 0x4b, 0x12,
	0x25, 0x98, 0x14, 0x98, 0x35, 0xb8, 0x8d, 0x04, 0xf4, 0xd0, 0xac, 0x0f, 0x02, 0xcb, 0x1a, 0xbd,
	0x61, 0xe4, 0x62, 0x87, 0xca, 0x08, 0x19, 0x73, 0x71, 0xb9, 0xa7, 0x96, 0x40, 0x4d, 0x17, 0xe2,
	0xd7, 0x43, 0xf5, 0xb4, 0x94, 0x88, 0x1e, 0x36, 0xcb, 0x4d, 0xb9, 0xb8, 0x1c, 0x53, 0x52, 0x60,
	0x46, 0x60, 0x68, 0x12, 0xd3, 0x83, 0x84, 0xac, 0x1e, 0x2c, 0x64, 0xf5, 0x5c, 0x41, 0x21, 0x2b,
	0x64, 0xc1, 0xc5, 0xeb, 0x92, 0x9a, 0x93, 0x5a, 0x92, 0x4a, 0xb2, 0x4e, 0x6b, 0x2e, 0x01, 0xf7,
	0xd4, 0x12, 0xa8, 0x62, 0x97, 0xd4, 0x92, 0xc4, 0xcc, 0x1c, 0xa2, 0x35, 0x3b, 0x71, 0x46, 0xb1,
	0xeb, 0x59, 0x43, 0xc4, 0xd8, 0xc0, 0x94, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x7e, 0xcd, 0x8c,
	0xeb, 0x0a, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// UserFavClient is the client API for UserFav service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserFavClient interface {
	GetFavList(ctx context.Context, in *UserFavRequest, opts ...grpc.CallOption) (*UserFavListResponse, error)
	AddUserFav(ctx context.Context, in *UserFavRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	DeleteUserFav(ctx context.Context, in *UserFavRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	GetUserFavDetail(ctx context.Context, in *UserFavRequest, opts ...grpc.CallOption) (*empty.Empty, error)
}

type userFavClient struct {
	cc grpc.ClientConnInterface
}

func NewUserFavClient(cc grpc.ClientConnInterface) UserFavClient {
	return &userFavClient{cc}
}

func (c *userFavClient) GetFavList(ctx context.Context, in *UserFavRequest, opts ...grpc.CallOption) (*UserFavListResponse, error) {
	out := new(UserFavListResponse)
	err := c.cc.Invoke(ctx, "/UserFav/GetFavList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userFavClient) AddUserFav(ctx context.Context, in *UserFavRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/UserFav/AddUserFav", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userFavClient) DeleteUserFav(ctx context.Context, in *UserFavRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/UserFav/DeleteUserFav", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userFavClient) GetUserFavDetail(ctx context.Context, in *UserFavRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/UserFav/GetUserFavDetail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserFavServer is the server API for UserFav service.
type UserFavServer interface {
	GetFavList(context.Context, *UserFavRequest) (*UserFavListResponse, error)
	AddUserFav(context.Context, *UserFavRequest) (*empty.Empty, error)
	DeleteUserFav(context.Context, *UserFavRequest) (*empty.Empty, error)
	GetUserFavDetail(context.Context, *UserFavRequest) (*empty.Empty, error)
}

// UnimplementedUserFavServer can be embedded to have forward compatible implementations.
type UnimplementedUserFavServer struct {
}

func (*UnimplementedUserFavServer) GetFavList(ctx context.Context, req *UserFavRequest) (*UserFavListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFavList not implemented")
}
func (*UnimplementedUserFavServer) AddUserFav(ctx context.Context, req *UserFavRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddUserFav not implemented")
}
func (*UnimplementedUserFavServer) DeleteUserFav(ctx context.Context, req *UserFavRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteUserFav not implemented")
}
func (*UnimplementedUserFavServer) GetUserFavDetail(ctx context.Context, req *UserFavRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserFavDetail not implemented")
}

func RegisterUserFavServer(s *grpc.Server, srv UserFavServer) {
	s.RegisterService(&_UserFav_serviceDesc, srv)
}

func _UserFav_GetFavList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserFavRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserFavServer).GetFavList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/UserFav/GetFavList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserFavServer).GetFavList(ctx, req.(*UserFavRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserFav_AddUserFav_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserFavRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserFavServer).AddUserFav(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/UserFav/AddUserFav",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserFavServer).AddUserFav(ctx, req.(*UserFavRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserFav_DeleteUserFav_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserFavRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserFavServer).DeleteUserFav(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/UserFav/DeleteUserFav",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserFavServer).DeleteUserFav(ctx, req.(*UserFavRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserFav_GetUserFavDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserFavRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserFavServer).GetUserFavDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/UserFav/GetUserFavDetail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserFavServer).GetUserFavDetail(ctx, req.(*UserFavRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserFav_serviceDesc = grpc.ServiceDesc{
	ServiceName: "UserFav",
	HandlerType: (*UserFavServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFavList",
			Handler:    _UserFav_GetFavList_Handler,
		},
		{
			MethodName: "AddUserFav",
			Handler:    _UserFav_AddUserFav_Handler,
		},
		{
			MethodName: "DeleteUserFav",
			Handler:    _UserFav_DeleteUserFav_Handler,
		},
		{
			MethodName: "GetUserFavDetail",
			Handler:    _UserFav_GetUserFavDetail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "userfav.proto",
}
