// Code generated by protoc-gen-go. DO NOT EDIT.
// source: order.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserInfo struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfo) Reset()         { *m = UserInfo{} }
func (m *UserInfo) String() string { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()    {}
func (*UserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{0}
}

func (m *UserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfo.Unmarshal(m, b)
}
func (m *UserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfo.Marshal(b, m, deterministic)
}
func (m *UserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfo.Merge(m, src)
}
func (m *UserInfo) XXX_Size() int {
	return xxx_messageInfo_UserInfo.Size(m)
}
func (m *UserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfo proto.InternalMessageInfo

func (m *UserInfo) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type CartItemListResponse struct {
	Total                int32                   `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Data                 []*ShopCartInfoResponse `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *CartItemListResponse) Reset()         { *m = CartItemListResponse{} }
func (m *CartItemListResponse) String() string { return proto.CompactTextString(m) }
func (*CartItemListResponse) ProtoMessage()    {}
func (*CartItemListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{1}
}

func (m *CartItemListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CartItemListResponse.Unmarshal(m, b)
}
func (m *CartItemListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CartItemListResponse.Marshal(b, m, deterministic)
}
func (m *CartItemListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CartItemListResponse.Merge(m, src)
}
func (m *CartItemListResponse) XXX_Size() int {
	return xxx_messageInfo_CartItemListResponse.Size(m)
}
func (m *CartItemListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CartItemListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CartItemListResponse proto.InternalMessageInfo

func (m *CartItemListResponse) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *CartItemListResponse) GetData() []*ShopCartInfoResponse {
	if m != nil {
		return m.Data
	}
	return nil
}

type ShopCartInfoResponse struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               int32    `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	GoodsId              int32    `protobuf:"varint,3,opt,name=goodsId,proto3" json:"goodsId,omitempty"`
	Num                  int32    `protobuf:"varint,4,opt,name=num,proto3" json:"num,omitempty"`
	Checked              bool     `protobuf:"varint,5,opt,name=checked,proto3" json:"checked,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShopCartInfoResponse) Reset()         { *m = ShopCartInfoResponse{} }
func (m *ShopCartInfoResponse) String() string { return proto.CompactTextString(m) }
func (*ShopCartInfoResponse) ProtoMessage()    {}
func (*ShopCartInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{2}
}

func (m *ShopCartInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShopCartInfoResponse.Unmarshal(m, b)
}
func (m *ShopCartInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShopCartInfoResponse.Marshal(b, m, deterministic)
}
func (m *ShopCartInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShopCartInfoResponse.Merge(m, src)
}
func (m *ShopCartInfoResponse) XXX_Size() int {
	return xxx_messageInfo_ShopCartInfoResponse.Size(m)
}
func (m *ShopCartInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ShopCartInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ShopCartInfoResponse proto.InternalMessageInfo

func (m *ShopCartInfoResponse) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ShopCartInfoResponse) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *ShopCartInfoResponse) GetGoodsId() int32 {
	if m != nil {
		return m.GoodsId
	}
	return 0
}

func (m *ShopCartInfoResponse) GetNum() int32 {
	if m != nil {
		return m.Num
	}
	return 0
}

func (m *ShopCartInfoResponse) GetChecked() bool {
	if m != nil {
		return m.Checked
	}
	return false
}

type CartItemRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               int32    `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	GoodsId              int32    `protobuf:"varint,3,opt,name=goodsId,proto3" json:"goodsId,omitempty"`
	Num                  int32    `protobuf:"varint,4,opt,name=num,proto3" json:"num,omitempty"`
	Checked              bool     `protobuf:"varint,5,opt,name=checked,proto3" json:"checked,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CartItemRequest) Reset()         { *m = CartItemRequest{} }
func (m *CartItemRequest) String() string { return proto.CompactTextString(m) }
func (*CartItemRequest) ProtoMessage()    {}
func (*CartItemRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{3}
}

func (m *CartItemRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CartItemRequest.Unmarshal(m, b)
}
func (m *CartItemRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CartItemRequest.Marshal(b, m, deterministic)
}
func (m *CartItemRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CartItemRequest.Merge(m, src)
}
func (m *CartItemRequest) XXX_Size() int {
	return xxx_messageInfo_CartItemRequest.Size(m)
}
func (m *CartItemRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CartItemRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CartItemRequest proto.InternalMessageInfo

func (m *CartItemRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CartItemRequest) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *CartItemRequest) GetGoodsId() int32 {
	if m != nil {
		return m.GoodsId
	}
	return 0
}

func (m *CartItemRequest) GetNum() int32 {
	if m != nil {
		return m.Num
	}
	return 0
}

func (m *CartItemRequest) GetChecked() bool {
	if m != nil {
		return m.Checked
	}
	return false
}

type OrderRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               int32    `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	Address              string   `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Mobile               string   `protobuf:"bytes,5,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Post                 string   `protobuf:"bytes,6,opt,name=post,proto3" json:"post,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderRequest) Reset()         { *m = OrderRequest{} }
func (m *OrderRequest) String() string { return proto.CompactTextString(m) }
func (*OrderRequest) ProtoMessage()    {}
func (*OrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{4}
}

func (m *OrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderRequest.Unmarshal(m, b)
}
func (m *OrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderRequest.Marshal(b, m, deterministic)
}
func (m *OrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderRequest.Merge(m, src)
}
func (m *OrderRequest) XXX_Size() int {
	return xxx_messageInfo_OrderRequest.Size(m)
}
func (m *OrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OrderRequest proto.InternalMessageInfo

func (m *OrderRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *OrderRequest) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *OrderRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *OrderRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *OrderRequest) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *OrderRequest) GetPost() string {
	if m != nil {
		return m.Post
	}
	return ""
}

type OrderInfoResponse struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               int32    `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	OrderSn              string   `protobuf:"bytes,3,opt,name=orderSn,proto3" json:"orderSn,omitempty"`
	PayType              string   `protobuf:"bytes,4,opt,name=payType,proto3" json:"payType,omitempty"`
	Status               string   `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Post                 string   `protobuf:"bytes,6,opt,name=post,proto3" json:"post,omitempty"`
	Total                float32  `protobuf:"fixed32,7,opt,name=total,proto3" json:"total,omitempty"`
	Address              string   `protobuf:"bytes,8,opt,name=address,proto3" json:"address,omitempty"`
	Name                 string   `protobuf:"bytes,9,opt,name=name,proto3" json:"name,omitempty"`
	Mobile               string   `protobuf:"bytes,10,opt,name=mobile,proto3" json:"mobile,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderInfoResponse) Reset()         { *m = OrderInfoResponse{} }
func (m *OrderInfoResponse) String() string { return proto.CompactTextString(m) }
func (*OrderInfoResponse) ProtoMessage()    {}
func (*OrderInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{5}
}

func (m *OrderInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderInfoResponse.Unmarshal(m, b)
}
func (m *OrderInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderInfoResponse.Marshal(b, m, deterministic)
}
func (m *OrderInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderInfoResponse.Merge(m, src)
}
func (m *OrderInfoResponse) XXX_Size() int {
	return xxx_messageInfo_OrderInfoResponse.Size(m)
}
func (m *OrderInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OrderInfoResponse proto.InternalMessageInfo

func (m *OrderInfoResponse) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *OrderInfoResponse) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *OrderInfoResponse) GetOrderSn() string {
	if m != nil {
		return m.OrderSn
	}
	return ""
}

func (m *OrderInfoResponse) GetPayType() string {
	if m != nil {
		return m.PayType
	}
	return ""
}

func (m *OrderInfoResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *OrderInfoResponse) GetPost() string {
	if m != nil {
		return m.Post
	}
	return ""
}

func (m *OrderInfoResponse) GetTotal() float32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *OrderInfoResponse) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *OrderInfoResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *OrderInfoResponse) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

type OrderFilterRequest struct {
	UserId               int32    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Pages                int32    `protobuf:"varint,2,opt,name=pages,proto3" json:"pages,omitempty"`
	PagePerNums          int32    `protobuf:"varint,3,opt,name=pagePerNums,proto3" json:"pagePerNums,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderFilterRequest) Reset()         { *m = OrderFilterRequest{} }
func (m *OrderFilterRequest) String() string { return proto.CompactTextString(m) }
func (*OrderFilterRequest) ProtoMessage()    {}
func (*OrderFilterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{6}
}

func (m *OrderFilterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderFilterRequest.Unmarshal(m, b)
}
func (m *OrderFilterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderFilterRequest.Marshal(b, m, deterministic)
}
func (m *OrderFilterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderFilterRequest.Merge(m, src)
}
func (m *OrderFilterRequest) XXX_Size() int {
	return xxx_messageInfo_OrderFilterRequest.Size(m)
}
func (m *OrderFilterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderFilterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OrderFilterRequest proto.InternalMessageInfo

func (m *OrderFilterRequest) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *OrderFilterRequest) GetPages() int32 {
	if m != nil {
		return m.Pages
	}
	return 0
}

func (m *OrderFilterRequest) GetPagePerNums() int32 {
	if m != nil {
		return m.PagePerNums
	}
	return 0
}

type OrderListResponse struct {
	Total                int32                `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Data                 []*OrderInfoResponse `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *OrderListResponse) Reset()         { *m = OrderListResponse{} }
func (m *OrderListResponse) String() string { return proto.CompactTextString(m) }
func (*OrderListResponse) ProtoMessage()    {}
func (*OrderListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{7}
}

func (m *OrderListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderListResponse.Unmarshal(m, b)
}
func (m *OrderListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderListResponse.Marshal(b, m, deterministic)
}
func (m *OrderListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderListResponse.Merge(m, src)
}
func (m *OrderListResponse) XXX_Size() int {
	return xxx_messageInfo_OrderListResponse.Size(m)
}
func (m *OrderListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OrderListResponse proto.InternalMessageInfo

func (m *OrderListResponse) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *OrderListResponse) GetData() []*OrderInfoResponse {
	if m != nil {
		return m.Data
	}
	return nil
}

type OrderInfoDetailRes struct {
	OrderInfo            *OrderInfoResponse   `protobuf:"bytes,1,opt,name=orderInfo,proto3" json:"orderInfo,omitempty"`
	Goods                []*OrderItemResponse `protobuf:"bytes,2,rep,name=goods,proto3" json:"goods,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *OrderInfoDetailRes) Reset()         { *m = OrderInfoDetailRes{} }
func (m *OrderInfoDetailRes) String() string { return proto.CompactTextString(m) }
func (*OrderInfoDetailRes) ProtoMessage()    {}
func (*OrderInfoDetailRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{8}
}

func (m *OrderInfoDetailRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderInfoDetailRes.Unmarshal(m, b)
}
func (m *OrderInfoDetailRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderInfoDetailRes.Marshal(b, m, deterministic)
}
func (m *OrderInfoDetailRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderInfoDetailRes.Merge(m, src)
}
func (m *OrderInfoDetailRes) XXX_Size() int {
	return xxx_messageInfo_OrderInfoDetailRes.Size(m)
}
func (m *OrderInfoDetailRes) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderInfoDetailRes.DiscardUnknown(m)
}

var xxx_messageInfo_OrderInfoDetailRes proto.InternalMessageInfo

func (m *OrderInfoDetailRes) GetOrderInfo() *OrderInfoResponse {
	if m != nil {
		return m.OrderInfo
	}
	return nil
}

func (m *OrderInfoDetailRes) GetGoods() []*OrderItemResponse {
	if m != nil {
		return m.Goods
	}
	return nil
}

type OrderItemResponse struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderId              int32    `protobuf:"varint,2,opt,name=orderId,proto3" json:"orderId,omitempty"`
	GoodsId              int32    `protobuf:"varint,3,opt,name=goodsId,proto3" json:"goodsId,omitempty"`
	GoodsName            string   `protobuf:"bytes,4,opt,name=goodsName,proto3" json:"goodsName,omitempty"`
	GoodsImage           string   `protobuf:"bytes,5,opt,name=goodsImage,proto3" json:"goodsImage,omitempty"`
	GoodsPrice           float32  `protobuf:"fixed32,6,opt,name=goodsPrice,proto3" json:"goodsPrice,omitempty"`
	Num                  int32    `protobuf:"varint,7,opt,name=num,proto3" json:"num,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderItemResponse) Reset()         { *m = OrderItemResponse{} }
func (m *OrderItemResponse) String() string { return proto.CompactTextString(m) }
func (*OrderItemResponse) ProtoMessage()    {}
func (*OrderItemResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{9}
}

func (m *OrderItemResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderItemResponse.Unmarshal(m, b)
}
func (m *OrderItemResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderItemResponse.Marshal(b, m, deterministic)
}
func (m *OrderItemResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderItemResponse.Merge(m, src)
}
func (m *OrderItemResponse) XXX_Size() int {
	return xxx_messageInfo_OrderItemResponse.Size(m)
}
func (m *OrderItemResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderItemResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OrderItemResponse proto.InternalMessageInfo

func (m *OrderItemResponse) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *OrderItemResponse) GetOrderId() int32 {
	if m != nil {
		return m.OrderId
	}
	return 0
}

func (m *OrderItemResponse) GetGoodsId() int32 {
	if m != nil {
		return m.GoodsId
	}
	return 0
}

func (m *OrderItemResponse) GetGoodsName() string {
	if m != nil {
		return m.GoodsName
	}
	return ""
}

func (m *OrderItemResponse) GetGoodsImage() string {
	if m != nil {
		return m.GoodsImage
	}
	return ""
}

func (m *OrderItemResponse) GetGoodsPrice() float32 {
	if m != nil {
		return m.GoodsPrice
	}
	return 0
}

func (m *OrderItemResponse) GetNum() int32 {
	if m != nil {
		return m.Num
	}
	return 0
}

type OrderStatus struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderSn              string   `protobuf:"bytes,2,opt,name=orderSn,proto3" json:"orderSn,omitempty"`
	Status               string   `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderStatus) Reset()         { *m = OrderStatus{} }
func (m *OrderStatus) String() string { return proto.CompactTextString(m) }
func (*OrderStatus) ProtoMessage()    {}
func (*OrderStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{10}
}

func (m *OrderStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderStatus.Unmarshal(m, b)
}
func (m *OrderStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderStatus.Marshal(b, m, deterministic)
}
func (m *OrderStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderStatus.Merge(m, src)
}
func (m *OrderStatus) XXX_Size() int {
	return xxx_messageInfo_OrderStatus.Size(m)
}
func (m *OrderStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderStatus.DiscardUnknown(m)
}

var xxx_messageInfo_OrderStatus proto.InternalMessageInfo

func (m *OrderStatus) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *OrderStatus) GetOrderSn() string {
	if m != nil {
		return m.OrderSn
	}
	return ""
}

func (m *OrderStatus) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func init() {
	proto.RegisterType((*UserInfo)(nil), "UserInfo")
	proto.RegisterType((*CartItemListResponse)(nil), "CartItemListResponse")
	proto.RegisterType((*ShopCartInfoResponse)(nil), "ShopCartInfoResponse")
	proto.RegisterType((*CartItemRequest)(nil), "CartItemRequest")
	proto.RegisterType((*OrderRequest)(nil), "OrderRequest")
	proto.RegisterType((*OrderInfoResponse)(nil), "OrderInfoResponse")
	proto.RegisterType((*OrderFilterRequest)(nil), "OrderFilterRequest")
	proto.RegisterType((*OrderListResponse)(nil), "OrderListResponse")
	proto.RegisterType((*OrderInfoDetailRes)(nil), "OrderInfoDetailRes")
	proto.RegisterType((*OrderItemResponse)(nil), "OrderItemResponse")
	proto.RegisterType((*OrderStatus)(nil), "OrderStatus")
}

func init() { proto.RegisterFile("order.proto", fileDescriptor_cd01338c35d87077) }

var fileDescriptor_cd01338c35d87077 = []byte{
	// 659 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x55, 0xcf, 0x4e, 0xdc, 0x3c,
	0x10, 0x57, 0xb2, 0x84, 0x25, 0xb3, 0x7c, 0x7c, 0x60, 0x16, 0x14, 0x6d, 0xab, 0x6a, 0x95, 0x43,
	0xb5, 0xbd, 0x18, 0x4a, 0x7b, 0xa1, 0xbd, 0x15, 0x5a, 0x09, 0xa9, 0x02, 0x9a, 0x2d, 0xaa, 0xd4,
	0x9b, 0xc1, 0x66, 0x89, 0x9a, 0xc4, 0x69, 0xec, 0x1c, 0x38, 0xf5, 0xd2, 0x07, 0xe8, 0x33, 0xf5,
	0xd2, 0x47, 0xea, 0xb5, 0xb2, 0x1d, 0x6f, 0xcc, 0x12, 0x50, 0xc5, 0xa1, 0xa7, 0xf8, 0x37, 0x33,
	0xf6, 0xfc, 0xfb, 0xcd, 0x04, 0x06, 0xbc, 0xa2, 0xac, 0xc2, 0x65, 0xc5, 0x25, 0x1f, 0x3d, 0x9a,
	0x71, 0x3e, 0xcb, 0xd8, 0x8e, 0x46, 0xe7, 0xf5, 0xe5, 0x0e, 0xcb, 0x4b, 0x79, 0x6d, 0x94, 0xf1,
	0x08, 0x56, 0xce, 0x04, 0xab, 0x8e, 0x8a, 0x4b, 0x8e, 0xd6, 0xc0, 0x4f, 0x69, 0xe4, 0x8d, 0xbd,
	0x49, 0x90, 0xf8, 0x29, 0x8d, 0x3f, 0xc1, 0xf0, 0x80, 0x54, 0xf2, 0x48, 0xb2, 0xfc, 0x7d, 0x2a,
	0x64, 0xc2, 0x44, 0xc9, 0x0b, 0xc1, 0xd0, 0x10, 0x02, 0xc9, 0x25, 0xc9, 0x1a, 0x53, 0x03, 0xd0,
	0x33, 0x58, 0xa2, 0x44, 0x92, 0xc8, 0x1f, 0xf7, 0x26, 0x83, 0xbd, 0x2d, 0x3c, 0xbd, 0xe2, 0xa5,
	0xbe, 0x5e, 0x5c, 0x72, 0x7b, 0x35, 0xd1, 0x26, 0xf1, 0x77, 0x0f, 0x86, 0x5d, 0xea, 0xc5, 0x08,
	0xd0, 0x36, 0x2c, 0xd7, 0x2a, 0x3a, 0x1a, 0xf9, 0x5a, 0xd6, 0x20, 0x14, 0x41, 0x7f, 0xc6, 0x39,
	0x15, 0x47, 0x34, 0xea, 0x69, 0x85, 0x85, 0x68, 0x1d, 0x7a, 0x45, 0x9d, 0x47, 0x4b, 0x5a, 0xaa,
	0x8e, 0xca, 0xf6, 0xe2, 0x8a, 0x5d, 0x7c, 0x61, 0x34, 0x0a, 0xc6, 0xde, 0x64, 0x25, 0xb1, 0x30,
	0xfe, 0x06, 0xff, 0xdb, 0xfc, 0x12, 0xf6, 0xb5, 0x66, 0x42, 0xfe, 0xe3, 0x00, 0x7e, 0x78, 0xb0,
	0x7a, 0xa2, 0x3a, 0xf5, 0x00, 0xf7, 0x84, 0xd2, 0x8a, 0x09, 0xa1, 0xdd, 0x87, 0x89, 0x85, 0x08,
	0xc1, 0x52, 0x41, 0x72, 0xa6, 0xfd, 0x87, 0x89, 0x3e, 0xab, 0x57, 0x72, 0x7e, 0x9e, 0x66, 0x4c,
	0xfb, 0x0f, 0x93, 0x06, 0x29, 0xdb, 0x92, 0x0b, 0x19, 0x2d, 0x1b, 0x5b, 0x75, 0x8e, 0x7f, 0x7b,
	0xb0, 0xa1, 0x43, 0x7a, 0x68, 0x5f, 0x34, 0xf3, 0xa6, 0x85, 0x8d, 0xab, 0x81, 0x4a, 0x53, 0x92,
	0xeb, 0x8f, 0xd7, 0xa5, 0x0d, 0xcd, 0x42, 0xf5, 0x96, 0x90, 0x44, 0xd6, 0xc2, 0x46, 0x67, 0x50,
	0x57, 0x74, 0x2d, 0xf3, 0xfa, 0x63, 0x6f, 0xe2, 0x5b, 0xe6, 0x39, 0xd5, 0x58, 0xe9, 0xae, 0x46,
	0xd8, 0x59, 0x0d, 0x70, 0xab, 0x11, 0x53, 0x40, 0x3a, 0xf1, 0x77, 0x69, 0x26, 0xdb, 0x8e, 0xb4,
	0x99, 0x7a, 0x37, 0x32, 0x1d, 0x42, 0x50, 0x92, 0x19, 0x13, 0x4d, 0x01, 0x0c, 0x40, 0x63, 0x18,
	0xa8, 0xc3, 0x29, 0xab, 0x8e, 0xeb, 0x5c, 0x34, 0xd4, 0x70, 0x45, 0xf1, 0x87, 0xa6, 0xbc, 0x7f,
	0x31, 0x50, 0x4f, 0x6f, 0x0c, 0x14, 0xc2, 0xb7, 0xda, 0xd2, 0x4c, 0x53, 0xd9, 0x04, 0xae, 0x54,
	0x87, 0x4c, 0x92, 0x34, 0x4b, 0x98, 0x40, 0xbb, 0x10, 0x72, 0x2b, 0xd5, 0xef, 0x76, 0x3f, 0xd1,
	0x1a, 0xa1, 0x09, 0x04, 0x9a, 0xc4, 0x0b, 0x0e, 0xf5, 0x74, 0x34, 0xd6, 0xc6, 0x20, 0xfe, 0x35,
	0x27, 0x89, 0xa3, 0xbc, 0x45, 0x12, 0x4b, 0x86, 0x39, 0x4b, 0x2c, 0xbc, 0x67, 0x7a, 0x1e, 0x43,
	0xa8, 0x8f, 0xc7, 0x2d, 0x87, 0x5b, 0x01, 0x7a, 0x02, 0x60, 0x0c, 0x73, 0x32, 0xb3, 0x64, 0x76,
	0x24, 0x73, 0xfd, 0x69, 0x95, 0x5e, 0x30, 0x4d, 0x1c, 0x3f, 0x71, 0x24, 0x76, 0x36, 0xfb, 0xf3,
	0xd9, 0x8c, 0x4f, 0x60, 0xa0, 0x13, 0x99, 0x1a, 0xce, 0xdd, 0x95, 0xc2, 0xb4, 0xd0, 0x29, 0x38,
	0x7c, 0x6e, 0x59, 0xdb, 0x73, 0x59, 0xbb, 0xf7, 0xb3, 0x07, 0x81, 0x7e, 0x11, 0xed, 0xc2, 0xaa,
	0xbb, 0x3d, 0x51, 0x88, 0xed, 0xa2, 0x1d, 0x6d, 0xe1, 0xce, 0xbd, 0xba, 0x0f, 0x6b, 0x07, 0x15,
	0x23, 0x92, 0x59, 0x2d, 0x5a, 0xc7, 0x0b, 0x0b, 0x6a, 0xd4, 0xbd, 0x57, 0xd1, 0x2b, 0x58, 0x3b,
	0x2b, 0xe9, 0xfd, 0x57, 0xb7, 0xb1, 0xf9, 0x11, 0x60, 0xfb, 0x23, 0xc0, 0x6f, 0xd5, 0x8f, 0x40,
	0xdd, 0x3d, 0x64, 0x19, 0x7b, 0xd0, 0xdd, 0x5d, 0x18, 0x98, 0x90, 0x4d, 0xce, 0xff, 0x61, 0x77,
	0x9d, 0x8d, 0x3a, 0x08, 0x87, 0x5e, 0x42, 0x38, 0x1f, 0x00, 0xb4, 0x89, 0x6f, 0x8f, 0x9c, 0xbd,
	0x75, 0xa3, 0x34, 0xcf, 0x9b, 0x3e, 0x19, 0x7e, 0x2f, 0xfa, 0xd9, 0xc4, 0x1d, 0x03, 0xb0, 0x0f,
	0x1b, 0xa6, 0x24, 0x6e, 0x83, 0x57, 0xb1, 0x83, 0xee, 0xca, 0xea, 0x4d, 0xf8, 0xb9, 0x8f, 0x5f,
	0x1b, 0xd9, 0xb2, 0xfe, 0xbc, 0xf8, 0x13, 0x00, 0x00, 0xff, 0xff, 0x4d, 0xa2, 0x08, 0x5a, 0x52,
	0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// OrderClient is the client API for Order service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OrderClient interface {
	//购物车相关
	CartItemList(ctx context.Context, in *UserInfo, opts ...grpc.CallOption) (*CartItemListResponse, error)
	CreateCartItem(ctx context.Context, in *CartItemRequest, opts ...grpc.CallOption) (*ShopCartInfoResponse, error)
	UpdateCartItem(ctx context.Context, in *CartItemRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	DeleteCartItem(ctx context.Context, in *CartItemRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	//订单相关的功能
	CreateOrder(ctx context.Context, in *OrderRequest, opts ...grpc.CallOption) (*OrderInfoResponse, error)
	OrderList(ctx context.Context, in *OrderFilterRequest, opts ...grpc.CallOption) (*OrderListResponse, error)
	OrderDetail(ctx context.Context, in *OrderRequest, opts ...grpc.CallOption) (*OrderInfoDetailRes, error)
	UpdateOrderStatus(ctx context.Context, in *OrderStatus, opts ...grpc.CallOption) (*empty.Empty, error)
}

type orderClient struct {
	cc grpc.ClientConnInterface
}

func NewOrderClient(cc grpc.ClientConnInterface) OrderClient {
	return &orderClient{cc}
}

func (c *orderClient) CartItemList(ctx context.Context, in *UserInfo, opts ...grpc.CallOption) (*CartItemListResponse, error) {
	out := new(CartItemListResponse)
	err := c.cc.Invoke(ctx, "/Order/CartItemList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderClient) CreateCartItem(ctx context.Context, in *CartItemRequest, opts ...grpc.CallOption) (*ShopCartInfoResponse, error) {
	out := new(ShopCartInfoResponse)
	err := c.cc.Invoke(ctx, "/Order/CreateCartItem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderClient) UpdateCartItem(ctx context.Context, in *CartItemRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/Order/UpdateCartItem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderClient) DeleteCartItem(ctx context.Context, in *CartItemRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/Order/DeleteCartItem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderClient) CreateOrder(ctx context.Context, in *OrderRequest, opts ...grpc.CallOption) (*OrderInfoResponse, error) {
	out := new(OrderInfoResponse)
	err := c.cc.Invoke(ctx, "/Order/CreateOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderClient) OrderList(ctx context.Context, in *OrderFilterRequest, opts ...grpc.CallOption) (*OrderListResponse, error) {
	out := new(OrderListResponse)
	err := c.cc.Invoke(ctx, "/Order/OrderList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderClient) OrderDetail(ctx context.Context, in *OrderRequest, opts ...grpc.CallOption) (*OrderInfoDetailRes, error) {
	out := new(OrderInfoDetailRes)
	err := c.cc.Invoke(ctx, "/Order/OrderDetail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderClient) UpdateOrderStatus(ctx context.Context, in *OrderStatus, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/Order/UpdateOrderStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderServer is the server API for Order service.
type OrderServer interface {
	//购物车相关
	CartItemList(context.Context, *UserInfo) (*CartItemListResponse, error)
	CreateCartItem(context.Context, *CartItemRequest) (*ShopCartInfoResponse, error)
	UpdateCartItem(context.Context, *CartItemRequest) (*empty.Empty, error)
	DeleteCartItem(context.Context, *CartItemRequest) (*empty.Empty, error)
	//订单相关的功能
	CreateOrder(context.Context, *OrderRequest) (*OrderInfoResponse, error)
	OrderList(context.Context, *OrderFilterRequest) (*OrderListResponse, error)
	OrderDetail(context.Context, *OrderRequest) (*OrderInfoDetailRes, error)
	UpdateOrderStatus(context.Context, *OrderStatus) (*empty.Empty, error)
}

// UnimplementedOrderServer can be embedded to have forward compatible implementations.
type UnimplementedOrderServer struct {
}

func (*UnimplementedOrderServer) CartItemList(ctx context.Context, req *UserInfo) (*CartItemListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CartItemList not implemented")
}
func (*UnimplementedOrderServer) CreateCartItem(ctx context.Context, req *CartItemRequest) (*ShopCartInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCartItem not implemented")
}
func (*UnimplementedOrderServer) UpdateCartItem(ctx context.Context, req *CartItemRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCartItem not implemented")
}
func (*UnimplementedOrderServer) DeleteCartItem(ctx context.Context, req *CartItemRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteCartItem not implemented")
}
func (*UnimplementedOrderServer) CreateOrder(ctx context.Context, req *OrderRequest) (*OrderInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateOrder not implemented")
}
func (*UnimplementedOrderServer) OrderList(ctx context.Context, req *OrderFilterRequest) (*OrderListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OrderList not implemented")
}
func (*UnimplementedOrderServer) OrderDetail(ctx context.Context, req *OrderRequest) (*OrderInfoDetailRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OrderDetail not implemented")
}
func (*UnimplementedOrderServer) UpdateOrderStatus(ctx context.Context, req *OrderStatus) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateOrderStatus not implemented")
}

func RegisterOrderServer(s *grpc.Server, srv OrderServer) {
	s.RegisterService(&_Order_serviceDesc, srv)
}

func _Order_CartItemList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServer).CartItemList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Order/CartItemList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServer).CartItemList(ctx, req.(*UserInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _Order_CreateCartItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CartItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServer).CreateCartItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Order/CreateCartItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServer).CreateCartItem(ctx, req.(*CartItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Order_UpdateCartItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CartItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServer).UpdateCartItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Order/UpdateCartItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServer).UpdateCartItem(ctx, req.(*CartItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Order_DeleteCartItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CartItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServer).DeleteCartItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Order/DeleteCartItem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServer).DeleteCartItem(ctx, req.(*CartItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Order_CreateOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServer).CreateOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Order/CreateOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServer).CreateOrder(ctx, req.(*OrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Order_OrderList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderFilterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServer).OrderList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Order/OrderList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServer).OrderList(ctx, req.(*OrderFilterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Order_OrderDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServer).OrderDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Order/OrderDetail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServer).OrderDetail(ctx, req.(*OrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Order_UpdateOrderStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderStatus)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServer).UpdateOrderStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Order/UpdateOrderStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServer).UpdateOrderStatus(ctx, req.(*OrderStatus))
	}
	return interceptor(ctx, in, info, handler)
}

var _Order_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Order",
	HandlerType: (*OrderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CartItemList",
			Handler:    _Order_CartItemList_Handler,
		},
		{
			MethodName: "CreateCartItem",
			Handler:    _Order_CreateCartItem_Handler,
		},
		{
			MethodName: "UpdateCartItem",
			Handler:    _Order_UpdateCartItem_Handler,
		},
		{
			MethodName: "DeleteCartItem",
			Handler:    _Order_DeleteCartItem_Handler,
		},
		{
			MethodName: "CreateOrder",
			Handler:    _Order_CreateOrder_Handler,
		},
		{
			MethodName: "OrderList",
			Handler:    _Order_OrderList_Handler,
		},
		{
			MethodName: "OrderDetail",
			Handler:    _Order_OrderDetail_Handler,
		},
		{
			MethodName: "UpdateOrderStatus",
			Handler:    _Order_UpdateOrderStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "order.proto",
}
