// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MessageRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               int32    `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	MessageType          int32    `protobuf:"varint,3,opt,name=messageType,proto3" json:"messageType,omitempty"`
	Subject              string   `protobuf:"bytes,4,opt,name=subject,proto3" json:"subject,omitempty"`
	Message              string   `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	File                 string   `protobuf:"bytes,6,opt,name=file,proto3" json:"file,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageRequest) Reset()         { *m = MessageRequest{} }
func (m *MessageRequest) String() string { return proto.CompactTextString(m) }
func (*MessageRequest) ProtoMessage()    {}
func (*MessageRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

func (m *MessageRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageRequest.Unmarshal(m, b)
}
func (m *MessageRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageRequest.Marshal(b, m, deterministic)
}
func (m *MessageRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageRequest.Merge(m, src)
}
func (m *MessageRequest) XXX_Size() int {
	return xxx_messageInfo_MessageRequest.Size(m)
}
func (m *MessageRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MessageRequest proto.InternalMessageInfo

func (m *MessageRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *MessageRequest) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *MessageRequest) GetMessageType() int32 {
	if m != nil {
		return m.MessageType
	}
	return 0
}

func (m *MessageRequest) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *MessageRequest) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *MessageRequest) GetFile() string {
	if m != nil {
		return m.File
	}
	return ""
}

type MessageResponse struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               int32    `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	MessageType          int32    `protobuf:"varint,3,opt,name=messageType,proto3" json:"messageType,omitempty"`
	Subject              string   `protobuf:"bytes,4,opt,name=subject,proto3" json:"subject,omitempty"`
	Message              string   `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	File                 string   `protobuf:"bytes,6,opt,name=file,proto3" json:"file,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageResponse) Reset()         { *m = MessageResponse{} }
func (m *MessageResponse) String() string { return proto.CompactTextString(m) }
func (*MessageResponse) ProtoMessage()    {}
func (*MessageResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}

func (m *MessageResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageResponse.Unmarshal(m, b)
}
func (m *MessageResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageResponse.Marshal(b, m, deterministic)
}
func (m *MessageResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageResponse.Merge(m, src)
}
func (m *MessageResponse) XXX_Size() int {
	return xxx_messageInfo_MessageResponse.Size(m)
}
func (m *MessageResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MessageResponse proto.InternalMessageInfo

func (m *MessageResponse) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *MessageResponse) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *MessageResponse) GetMessageType() int32 {
	if m != nil {
		return m.MessageType
	}
	return 0
}

func (m *MessageResponse) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *MessageResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *MessageResponse) GetFile() string {
	if m != nil {
		return m.File
	}
	return ""
}

type MessageListResponse struct {
	Total                int32              `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Data                 []*MessageResponse `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *MessageListResponse) Reset()         { *m = MessageListResponse{} }
func (m *MessageListResponse) String() string { return proto.CompactTextString(m) }
func (*MessageListResponse) ProtoMessage()    {}
func (*MessageListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{2}
}

func (m *MessageListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageListResponse.Unmarshal(m, b)
}
func (m *MessageListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageListResponse.Marshal(b, m, deterministic)
}
func (m *MessageListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageListResponse.Merge(m, src)
}
func (m *MessageListResponse) XXX_Size() int {
	return xxx_messageInfo_MessageListResponse.Size(m)
}
func (m *MessageListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MessageListResponse proto.InternalMessageInfo

func (m *MessageListResponse) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *MessageListResponse) GetData() []*MessageResponse {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*MessageRequest)(nil), "MessageRequest")
	proto.RegisterType((*MessageResponse)(nil), "MessageResponse")
	proto.RegisterType((*MessageListResponse)(nil), "MessageListResponse")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd) }

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 257 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x92, 0x3f, 0x4f, 0xc3, 0x30,
	0x10, 0xc5, 0xe5, 0x34, 0x7f, 0xd4, 0x8b, 0xda, 0xa2, 0xa3, 0x42, 0x16, 0x53, 0x54, 0x31, 0x64,
	0xf2, 0x10, 0xd8, 0xd8, 0x60, 0x42, 0x82, 0x81, 0x88, 0x89, 0xcd, 0x25, 0x07, 0x0a, 0x2a, 0x24,
	0xe4, 0x2e, 0x03, 0x5f, 0x07, 0xbe, 0x28, 0xc2, 0x71, 0xab, 0x42, 0xf8, 0x00, 0x4c, 0xc9, 0x7b,
	0xcf, 0x7e, 0xf7, 0xb3, 0x6c, 0x98, 0xbd, 0x10, 0xb3, 0x7d, 0x22, 0xd3, 0x76, 0x8d, 0x34, 0xab,
	0x0f, 0x05, 0xf3, 0x9b, 0xc1, 0x29, 0xe9, 0xad, 0x27, 0x16, 0x9c, 0x43, 0x50, 0x57, 0x5a, 0x65,
	0x2a, 0x8f, 0xca, 0xa0, 0xae, 0xf0, 0x08, 0xe2, 0x9e, 0xa9, 0xbb, 0xaa, 0x74, 0xe0, 0x3c, 0xaf,
	0x30, 0x83, 0xd4, 0x77, 0xdd, 0xbd, 0xb7, 0xa4, 0x27, 0x2e, 0xdc, 0xb7, 0x50, 0x43, 0xc2, 0xfd,
	0xfa, 0x99, 0x1e, 0x44, 0x87, 0x99, 0xca, 0xa7, 0xe5, 0x56, 0x7e, 0x27, 0x7e, 0xa1, 0x8e, 0x86,
	0xc4, 0x4b, 0x44, 0x08, 0x1f, 0xeb, 0x0d, 0xe9, 0xd8, 0xd9, 0xee, 0x7f, 0xf5, 0xa9, 0x60, 0xb1,
	0x83, 0xe4, 0xb6, 0x79, 0x65, 0xfa, 0x87, 0x94, 0xb7, 0x70, 0xe8, 0x21, 0xaf, 0x6b, 0x96, 0x1d,
	0xe8, 0x12, 0x22, 0x69, 0xc4, 0x6e, 0x3c, 0xeb, 0x20, 0xf0, 0x04, 0xc2, 0xca, 0x8a, 0xd5, 0x41,
	0x36, 0xc9, 0xd3, 0xe2, 0xc0, 0xfc, 0x3a, 0x5e, 0xe9, 0xd2, 0x82, 0x21, 0xf1, 0x01, 0x9e, 0x41,
	0xba, 0xd7, 0x8e, 0x0b, 0xf3, 0xf3, 0xd6, 0x8e, 0x97, 0xe6, 0xaf, 0xe1, 0x05, 0xcc, 0x2e, 0x3b,
	0xb2, 0x42, 0xdb, 0x9a, 0xd1, 0xbe, 0xd1, 0xe8, 0x8b, 0xe9, 0x7d, 0x62, 0xce, 0xdd, 0xeb, 0x58,
	0xc7, 0xee, 0x73, 0xfa, 0x15, 0x00, 0x00, 0xff, 0xff, 0x1b, 0x5b, 0x3a, 0xf0, 0x35, 0x02, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// MessageClient is the client API for Message service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MessageClient interface {
	MessageList(ctx context.Context, in *MessageRequest, opts ...grpc.CallOption) (*MessageListResponse, error)
	CreateMessage(ctx context.Context, in *MessageRequest, opts ...grpc.CallOption) (*MessageResponse, error)
}

type messageClient struct {
	cc grpc.ClientConnInterface
}

func NewMessageClient(cc grpc.ClientConnInterface) MessageClient {
	return &messageClient{cc}
}

func (c *messageClient) MessageList(ctx context.Context, in *MessageRequest, opts ...grpc.CallOption) (*MessageListResponse, error) {
	out := new(MessageListResponse)
	err := c.cc.Invoke(ctx, "/Message/MessageList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *messageClient) CreateMessage(ctx context.Context, in *MessageRequest, opts ...grpc.CallOption) (*MessageResponse, error) {
	out := new(MessageResponse)
	err := c.cc.Invoke(ctx, "/Message/CreateMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MessageServer is the server API for Message service.
type MessageServer interface {
	MessageList(context.Context, *MessageRequest) (*MessageListResponse, error)
	CreateMessage(context.Context, *MessageRequest) (*MessageResponse, error)
}

// UnimplementedMessageServer can be embedded to have forward compatible implementations.
type UnimplementedMessageServer struct {
}

func (*UnimplementedMessageServer) MessageList(ctx context.Context, req *MessageRequest) (*MessageListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MessageList not implemented")
}
func (*UnimplementedMessageServer) CreateMessage(ctx context.Context, req *MessageRequest) (*MessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateMessage not implemented")
}

func RegisterMessageServer(s *grpc.Server, srv MessageServer) {
	s.RegisterService(&_Message_serviceDesc, srv)
}

func _Message_MessageList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServer).MessageList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Message/MessageList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServer).MessageList(ctx, req.(*MessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Message_CreateMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MessageServer).CreateMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Message/CreateMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MessageServer).CreateMessage(ctx, req.(*MessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Message_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Message",
	HandlerType: (*MessageServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MessageList",
			Handler:    _Message_MessageList_Handler,
		},
		{
			MethodName: "CreateMessage",
			Handler:    _Message_CreateMessage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "message.proto",
}
